import { StyleSheet } from 'react-native';

export const rankingScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  backgroundPattern: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0A0A0A',
    opacity: 0.1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderBottomWidth: 1,
    borderBottomColor: '#00D1FF',
  },
  menuButton: {
    padding: 8,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00FF84',
    marginRight: 8,
    textShadowColor: '#00FF84',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  trophyIcon: {
    fontSize: 20,
  },
  avatarButton: {
    padding: 8,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#00FF84',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#00FF84',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  topThreeContainer: {
    marginTop: 20,
  },
  topThreeItem: {
    marginBottom: 15,
    position: 'relative',
  },
  confetti: {
    position: 'absolute',
    top: -10,
    right: -10,
    zIndex: 10,
  },
  confettiText: {
    fontSize: 24,
  },
  topThreeCard: {
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  rankBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  rankNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginRight: 10,
  },
  rankIcon: {
    fontSize: 24,
  },
  userInfo: {
    alignItems: 'center',
    marginBottom: 15,
  },
  avatarText: {
    fontSize: 32,
    marginBottom: 8,
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  userLevel: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.9,
    marginBottom: 8,
  },
  userPoints: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  progressContainer: {
    marginTop: 10,
  },
  progressBar: {
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  otherUsersContainer: {
    marginTop: 30,
  },
  otherUsersTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#00D1FF',
    marginBottom: 15,
    textShadowColor: '#00D1FF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  userCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#00D1FF',
    shadowColor: '#00D1FF',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  userCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  rankBadgeSmall: {
    backgroundColor: '#00FF84',
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    shadowColor: '#00FF84',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 3,
  },
  rankNumberSmall: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#fff',
  },
  avatarTextSmall: {
    fontSize: 20,
    marginRight: 12,
  },
  userInfoSmall: {
    flex: 1,
  },
  userNameSmall: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 2,
  },
  userLevelSmall: {
    fontSize: 12,
    color: '#00D1FF',
  },
  userCardRight: {
    alignItems: 'flex-end',
  },
  userPointsSmall: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#00FF84',
    marginBottom: 8,
  },
  progressBarSmall: {
    width: 80,
    height: 4,
    backgroundColor: '#e0e0e0',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFillSmall: {
    height: '100%',
    borderRadius: 2,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderTopWidth: 1,
    borderTopColor: '#00D1FF',
    paddingVertical: 10,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  activeTab: {
    backgroundColor: 'rgba(0, 255, 132, 0.1)',
  },
  tabLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  activeTabLabel: {
    color: '#00FF84',
    fontWeight: '600',
    textShadowColor: '#00FF84',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
});
